import { mkdir, open, rename, unlink } from 'node:fs/promises';
import { randomUUID } from 'node:crypto';
import path from 'node:path';

import { codeUnitCompare } from './errors.mjs';
import { sha256, stableStringify } from './io.mjs';

const nodeSetFields = Object.freeze([
  'relatedNodeIds',
  'prerequisiteIds',
  'evidenceIds',
  'permissionIds',
  'eventRefIds',
  'files',
  'symbols',
]);

function stableObjectSort(left, right) {
  const leftKey = left?.id ?? left?.ref ?? stableStringify(left);
  const rightKey = right?.id ?? right?.ref ?? stableStringify(right);
  return codeUnitCompare(`${leftKey}\0${stableStringify(left)}`, `${rightKey}\0${stableStringify(right)}`);
}

export function canonicalizeGraphProjection(projection) {
  const canonical = structuredClone(projection);
  canonical.nodes?.sort(stableObjectSort);
  canonical.edges?.sort(stableObjectSort);
  canonical.permissions?.sort(stableObjectSort);
  canonical.handoffReceipts?.sort(stableObjectSort);
  for (const node of canonical.nodes ?? []) {
    for (const field of nodeSetFields) node[field]?.sort(codeUnitCompare);
  }
  return canonical;
}

export function canonicalizeGraph(graph) {
  const canonical = canonicalizeGraphProjection(graph);
  canonical.acyclicEdgeTypes?.sort(codeUnitCompare);
  canonical.eventRefs?.sort(stableObjectSort);
  canonical.authority?.markdownSources?.sort(stableObjectSort);
  return canonical;
}

export function graphHash(graph) {
  return sha256(stableStringify(canonicalizeGraph(graph)));
}

export function renderGraphView(graph) {
  const nodes = [...graph.nodes].sort((left, right) => codeUnitCompare(left.id, right.id));
  const lines = [
    '<!-- Generated by dev-flow graph. Read-only view; edit the JSON Graph authority. -->',
    `# ${graph.graphKind === 'master' ? 'Master' : 'Loop'} Graph: ${graph.id}`,
    '',
    `- Schema: ${graph.schemaVersion}`,
    `- Revision: ${graph.revision}`,
    `- Authority: ${graph.authority.mode}`,
    `- Graph hash: ${graphHash(graph)}`,
    '',
    '## Nodes',
    '',
    '| ID | Type | Status | Ref |',
    '| --- | --- | --- | --- |',
    ...nodes.map((node) => `| ${node.id} | ${node.type} | ${node.status} | ${node.ref ?? ''} |`),
    '',
  ];
  return `${lines.join('\n')}\n`;
}

export async function atomicWriteText(destination, content) {
  await mkdir(path.dirname(destination), { recursive: true });
  const temporaryPath = path.join(
    path.dirname(destination),
    `.${path.basename(destination)}.${process.pid}.${randomUUID()}.tmp`,
  );
  let handle;
  try {
    handle = await open(temporaryPath, 'wx', 0o600);
    await handle.writeFile(content, 'utf8');
    await handle.sync();
    await handle.close();
    handle = undefined;
    await rename(temporaryPath, destination);
  } catch (error) {
    if (handle) await handle.close().catch(() => {});
    await unlink(temporaryPath).catch(() => {});
    throw error;
  }
}

export async function writeGraphView(destination, graph) {
  await atomicWriteText(destination, renderGraphView(graph));
}
